import { QuoteBreakdown, QuoteInput } from '../lib/pricing';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Register standard fonts
Font.register({
  family: 'Helvetica',
  fonts: [
    { src: 'https://fonts.gstatic.com/s/helveticaneue/v77/1Ptsg8zYS_SKggPNyC0IT4ttDfA.ttf' },
    { src: 'https://fonts.gstatic.com/s/helveticaneue/v77/1Ptsg8zYS_SKggPNyC0IT4ttDfA.ttf', fontWeight: 'bold' }
  ]
});

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 2,
    borderBottomColor: '#3B82F6',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    color: '#111827',
    marginBottom: 8,
    fontWeight: 'bold',
  },
  subtitle: {
    fontSize: 12,
    color: '#6B7280',
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  label: {
    fontSize: 12,
    color: '#4B5563',
  },
  value: {
    fontSize: 12,
    color: '#111827',
    fontWeight: 'bold',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    paddingTop: 10,
    borderTopWidth: 2,
    borderTopColor: '#3B82F6',
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#111827',
  },
  totalValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#3B82F6',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 10,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  }
});

interface QuotePDFProps {
  request: QuoteInput;
  breakdown: QuoteBreakdown;
  min: number;
  max: number;
}

export const QuotePDF = ({ request, breakdown, min, max }: QuotePDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Web Project Estimate</Text>
        <Text style={styles.subtitle}>Generated by Chromapages</Text>
      </View>

      <View style={styles.section}>
        <Text style={{ fontSize: 14, marginBottom: 15, fontWeight: 'bold', color: '#374151' }}>Project Details</Text>
        
        <View style={styles.row}>
          <Text style={styles.label}>Project Type</Text>
          <Text style={styles.value}>{request.siteType.toUpperCase()}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Pages Scoped</Text>
          <Text style={styles.value}>{request.pageCount}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Design Level</Text>
          <Text style={styles.value}>{request.designLevel.toUpperCase()}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Timeline</Text>
          <Text style={styles.value}>{request.timeline.toUpperCase()}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={{ fontSize: 14, marginBottom: 15, fontWeight: 'bold', color: '#374151' }}>Cost Breakdown</Text>
        
        <View style={styles.row}>
          <Text style={styles.label}>Base Construction</Text>
          <Text style={styles.value}>${breakdown.base.toLocaleString()}</Text>
        </View>
        
        {breakdown.pages > 0 && (
          <View style={styles.row}>
            <Text style={styles.label}>Additional Pages</Text>
            <Text style={styles.value}>+${breakdown.pages.toLocaleString()}</Text>
          </View>
        )}

        {breakdown.features > 0 && (
          <View style={styles.row}>
            <Text style={styles.label}>Features & Functionality</Text>
            <Text style={styles.value}>+${breakdown.features.toLocaleString()}</Text>
          </View>
        )}

        {breakdown.design > 0 && (
          <View style={styles.row}>
            <Text style={styles.label}>Design Premium</Text>
            <Text style={styles.value}>+${breakdown.design.toLocaleString()}</Text>
          </View>
        )}

        {breakdown.timeline !== 0 && (
          <View style={styles.row}>
            <Text style={styles.label}>Timeline Adjustment</Text>
            <Text style={styles.value}>{breakdown.timeline > 0 ? '+' : ''}${breakdown.timeline.toLocaleString()}</Text>
          </View>
        )}

        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Estimated Range</Text>
          <Text style={styles.totalValue}>${min.toLocaleString()} - ${max.toLocaleString()}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={{ fontSize: 12, color: '#6B7280', marginTop: 20, lineHeight: 1.5 }}>
          This estimate is preliminary and subject to final scoping. Features included: {request.features.join(', ') || 'Standard package'}.
        </Text>
      </View>

      <Text style={styles.footer}>
        Chromapages LLC • 2026 • Confidential Quote
      </Text>
    </Page>
  </Document>
);
